<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <RootNamespace>FSO.Server.Domain</RootNamespace>
    <AssemblyName>FSO.Server.Domain</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <IsAotCompatible>true</IsAotCompatible>
    <TrimMode>full</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSO.Common.Domain\FSO.Common.Domain.csproj" />
    <ProjectReference Include="..\FSO.Server.Database\FSO.Server.Database.csproj" />
    <ProjectReference Include="..\FSO.Server.Protocol\FSO.Server.Protocol.csproj" />
  </ItemGroup>

</Project>
