<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>WinExe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>FSO.Patcher</RootNamespace>
    <AssemblyName>update</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>patcher.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="patcher.ico" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
