<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <RootNamespace>FSO.Server.Protocol</RootNamespace>
    <AssemblyName>FSO.Server.Protocol</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <IsAotCompatible>True</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <IsAotCompatible>true</IsAotCompatible>
    <TrimMode>full</TrimMode>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSO.Server.Common\FSO.Server.Common.csproj" />
    <ProjectReference Include="..\tso.common\FSO.Common.csproj" />
    <ProjectReference Include="..\tso.files\FSO.Files.csproj" />
  </ItemGroup>

</Project>
