<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>FSO.Common.DataService</RootNamespace>
    <AssemblyName>FSO.Common.DataService</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSO.Common.Domain\FSO.Common.Domain.csproj" />
    <ProjectReference Include="..\tso.common\FSO.Common.csproj" />
    <ProjectReference Include="..\tso.content\FSO.Content.csproj" />
    <ProjectReference Include="..\tso.files\FSO.Files.csproj" />
  </ItemGroup>

</Project>
